### ISSUE TITLE
Double character appears after completion

### ISSUE THREAD

**Issue by dmalyuta** [Sodel-the-Vociferous/helm-company#9] opened 2017-06-05 17:11 UTC
Sometimes (not always), after completing a word, the completed word has its first character duplicated:

![double_character_bug](https://cloud.githubusercontent.com/assets/12475811/26794625/48f2d5bc-49d7-11e7-9776-2567eb95dffd.gif)

My system: Ubuntu 14.04.5, Emacs 25.2.1, `helm-company` master branch.

**Comment by Sodel-the-Vociferous** [comment] 2017-06-05 19:03
Thanks for the report! Fixed in `master`. Let me know if the fix works for you.

**Comment by dmalyuta** [comment] 2017-06-06 01:57
It has fixed it for the example in the above screencast, but on some proprietary code that I unfortunately cannot post a screencast of here, I am getting a similar bug. In short, what happens is:
```
namespace1::namespace2::pos
```
Then I trigger completion and select the cadidate `position`. What gets printed in the source code is:
```
namespace1::namespace2::positposition
```

**Comment by Sodel-the-Vociferous** [comment] 2017-06-06 07:42
I can't reproduce this. :( This is the test `foo.cpp` file I'm using.

    #include <string>
    #include <iostream>

    namespace namespace1 {
        namespace namespace2 {
            int position;
            int positionTwo;
        }
    };
    
    int main()
    {
        namespace1::namespace2::pos
    }

Anything I can change to make this code trigger your glitch when you try to complete `pos`?

**Comment by dmalyuta** [comment] 2017-06-06 07:46
To be sure, are you using Emacs 25.2.1 for both issues?

**Comment by Sodel-the-Vociferous** [comment] 2017-06-06 07:47
Yup. Emacs 25.2.1.

**Comment by dmalyuta** [comment] 2017-06-06 07:49
The code you use also works for me, so it does not reproduce the issue. I'll see later if I can come up with something.

**Comment by Sodel-the-Vociferous** [comment] 2017-06-06 07:50
Thank you!

**Comment by Sodel-the-Vociferous** [comment] 2018-02-13 06:28
I still cannot reproduce this issue, sorry. Unless you object, I'll close this issue.

**Comment by dmalyuta** [comment] 2018-02-14 09:36
I'm not using the package anymore (I think there were other issues...). So I can't say, sorry.

**Comment by Sodel-the-Vociferous** [comment] 2018-02-15 07:42
Alright, thanks anyway!

**Closed as completed by Sodel-the-Vociferous** 2018-02-15 07:42 UTC
Labels: bug
